from __future__ import annotations

from typing import Any

from core.definitions import lifecycle_statuses, operational_modes, risk_catalog


ARCHITECTURE_BLOCKS: list[dict[str, Any]] = [
    {
        "id": "core",
        "name": "Veyra Core",
        "role": "Awareness, active runtime loop, state, attention, model-assisted reasoning, decision, risk governance, verification, and patch generation.",
        "paths": ["core/", "awareness/", "decision/", "foresight/", "guardian/"],
        "status": "implemented",
        "validation_state": "local_self_tested",
    },
    {
        "id": "interface_adapter",
        "name": "Interface Adapter / Agent Adapter",
        "role": "Normalize multi-channel inbound events, connect real chat apps such as Feishu, and connect one or more validated Agent runtimes.",
        "paths": ["interface/"],
        "status": "implemented",
        "validation_state": "external_runtime_validation_pending",
    },
    {
        "id": "probes",
        "name": "Probe Tools",
        "role": "Run low-risk read-only checks for system, git, port, process, files, logs, and runtime status.",
        "paths": ["probes/"],
        "status": "implemented",
        "validation_state": "environment_dependent",
    },
    {
        "id": "memory_bridge",
        "name": "Memory Bridge",
        "role": "Read useful long-term memory summaries and write filtered task learnings.",
        "paths": ["memory_bridge/"],
        "status": "implemented",
        "validation_state": "external_provider_validation_pending",
    },
    {
        "id": "skills",
        "name": "Skill",
        "role": "Execute fixed, low-risk workflows that do not need a full Agent planner.",
        "paths": ["skills/"],
        "status": "implemented",
        "validation_state": "local_self_tested",
    },
    {
        "id": "tool_proxy",
        "name": "Tool Proxy",
        "role": "Interpose Guardian policy before shell, file, browser, and API operations.",
        "paths": ["tool_proxy/"],
        "status": "implemented",
        "validation_state": "executor_hooks_configurable",
    },
    {
        "id": "rollback_audit",
        "name": "Rollback / Audit",
        "role": "Record traces, snapshots, diffs, rollback actions, replayable execution evidence, and automatic compensation review jobs.",
        "paths": ["rollback_audit/", "state/*.jsonl", "state/snapshots/"],
        "status": "implemented",
        "validation_state": "local_self_tested",
    },
    {
        "id": "web_control_ui",
        "name": "Web Control UI",
        "role": "Expose awareness, runtime, action review, tool proxy, and rollback state to operators.",
        "paths": ["web/", "ui/"],
        "status": "implemented",
        "validation_state": "build_verified",
    },
]


CORE_MODULES: list[dict[str, str]] = [
    {"id": "runtime_entity", "path": "core/runtime_entity.py", "status": "p8_continuous_entity"},
    {"id": "awareness_loop", "path": "core/awareness_loop.py", "status": "p8_continuous_entity"},
    {"id": "active_runtime_loop", "path": "runtime/active_loop.py", "status": "p8_continuous_entity"},
    {"id": "runtime_cron", "path": "runtime/cron.py", "status": "p9_runtime_scheduler"},
    {"id": "attention_core", "path": "awareness/attention_core.py", "status": "mvp_foundation"},
    {"id": "context_anchor_binder", "path": "core/context_anchor_binder.py", "status": "cross_phase_context_hypothesis_foundation"},
    {"id": "context_binding_store", "path": "runtime/context_binding_store.py", "status": "cross_phase_owner_bound_replay_safe"},
    {"id": "cognitive_brief_contract", "path": "interface/cognitive_brief_contract.py", "status": "cross_phase_record_only_contract"},
    {"id": "read_only_cognitive_loop", "path": "runtime/read_only_cognitive_loop.py", "status": "cross_phase_record_only_shadow_evidence"},
    {"id": "situation_evaluator", "path": "core/situation_evaluator.py", "status": "phase1_event_scoped"},
    {"id": "general_situation_runtime", "path": "runtime/general_situation_runtime.py", "status": "phase2_structured_noncausal"},
    {"id": "general_attention_scheduler", "path": "awareness/general_attention_scheduler.py", "status": "phase2_information_only"},
    {"id": "attention_hypothesis_runtime", "path": "runtime/attention_hypothesis_runtime.py", "status": "cognitive_awakening_record_only"},
    {"id": "suggestion_outbox", "path": "runtime/suggestion_outbox.py", "status": "phase2_console_information_only"},
    {"id": "project_guardian_attention", "path": "runtime/project_guardian_attention_runtime.py", "status": "phase2_shadow"},
    {"id": "autonomy_policy", "path": "core/autonomy_policy.py", "status": "phase5_technical_complete_domain_scoped"},
    {"id": "playbook_registry", "path": "runtime/playbook_registry.py", "status": "phase5_builtin_immutable"},
    {"id": "agent_transport_authority_fence", "path": "runtime/authority_fence.py", "status": "phase5_scoped_canary"},
    {"id": "self_heal_playbook", "path": "runtime/self_heal_playbook.py", "status": "phase5_a2_scoped_canary"},
    {"id": "sandbox_repair_playbook", "path": "runtime/sandbox_repair_playbook.py", "status": "phase5_a3_private_sandbox_only"},
    {"id": "belief_uncertainty_core", "path": "awareness/belief_core.py", "status": "p8_deep_ttl"},
    {"id": "world_state", "path": "core/world_state.py", "status": "mvp_foundation"},
    {"id": "durable_case", "path": "runtime/durable_case_store.py", "status": "phase4_analysis_only"},
    {"id": "core_model_client", "path": "core/model_client.py", "status": "p6_model_assisted"},
    {"id": "core_reasoning", "path": "core/reasoning_core.py", "status": "p6_model_assisted"},
    {"id": "understanding_core", "path": "core/understanding_core.py", "status": "p10_understanding_first"},
    {"id": "cognition_pipeline", "path": "core/cognition_pipeline.py", "status": "p10_model_first_route_gate"},
    {"id": "capability_registry", "path": "core/capability_registry.py", "status": "p10_unified_capabilities"},
    {"id": "agency_core", "path": "core/agency_core.py", "status": "p8_proactive_runtime"},
    {"id": "commitment_core", "path": "core/commitment_core.py", "status": "p10_user_commitment_runtime"},
    {"id": "perception_layer", "path": "core/perception_layer.py", "status": "p6_model_assisted"},
    {"id": "persona_engine", "path": "core/persona_engine.py", "status": "mvp_foundation"},
    {"id": "decision_core", "path": "core/decision_core.py", "status": "p6_model_assisted"},
    {"id": "foresight_engine", "path": "core/foresight_engine.py", "status": "phase5_exact_effect_adapter"},
    {"id": "foresight_contract", "path": "core/foresight_contract.py", "status": "phase5_exact_effect_contract"},
    {"id": "foresight_runtime", "path": "runtime/foresight_runtime.py", "status": "phase5_residual_shadow_calibration"},
    {"id": "learning_record", "path": "core/learning_record.py", "status": "phase5_exact_categorical_feedback"},
    {"id": "learning_calibration", "path": "runtime/learning_calibration_runtime.py", "status": "phase5_shadow_calibration"},
    {"id": "performance_portfolio", "path": "runtime/performance_portfolio.py", "status": "phase5_read_only_shadow"},
    {"id": "provider_certification", "path": "interface/provider_certification.py", "status": "phase5_fail_closed_read_only"},
    {"id": "phase5_control_plane", "path": "routers/phase5.py", "status": "phase5_technical_complete_shadow_calibration"},
    {"id": "guardian_execution_controller", "path": "core/guardian_controller.py", "status": "mvp_foundation"},
    {"id": "verifier", "path": "core/verifier.py", "status": "p4_completed"},
    {"id": "context_patch_builder", "path": "core/context_patch_builder.py", "status": "mvp_foundation"},
    {"id": "agent_orchestrator", "path": "runtime/agent_orchestrator.py", "status": "p8_validated_multi_agent"},
    {"id": "replay_runtime", "path": "rollback_audit/replay_runtime.py", "status": "p9_guarded_auto_execute"},
    {"id": "context_drift_detector", "path": "core/context_drift_detector.py", "status": "p10_context_guard"},
    {"id": "runtime_trace_metrics", "path": "runtime/routing_metrics.py", "status": "p10_telemetry"},
]


STATE_DEFINITIONS: list[dict[str, Any]] = [
    {
        "id": "user_world",
        "file": "state/user/user_world.json",
        "owner": "WorldState.UserWorld",
        "purpose": "Current user goal, preferences, working style, and relevant user context cache.",
        "freshness": "task_scoped",
    },
    {
        "id": "user_commitments",
        "file": "state/user/user_commitments.json",
        "owner": "CommitmentCore",
        "purpose": "User commitments, schedules, and proactive push contracts.",
        "freshness": "event_scoped",
    },
    {
        "id": "user_goals",
        "file": "state/user/user_goals.json",
        "owner": "GoalCore",
        "purpose": "Long-running user goals, learning plans, permissions, and progress state.",
        "freshness": "event_scoped",
    },
    {
        "id": "local_world",
        "file": "state/local/local_world.json",
        "owner": "WorldState.LocalWorld",
        "purpose": "Current project, probes, runtime facts, and local execution environment.",
        "freshness": "ttl_probe_backed",
    },
    {
        "id": "external_world",
        "file": "state/external/external_world.json",
        "owner": "WorldState.ExternalWorld",
        "purpose": "Watchlist and external context summaries relevant to current goals.",
        "freshness": "ttl_source_backed",
    },
    {
        "id": "risk_state",
        "file": "state/runtime/risk_state.json",
        "owner": "Guardian",
        "purpose": "Current event/task risk assessments and active risk signals.",
        "freshness": "event_scoped",
    },
    {
        "id": "risk_policy",
        "file": "state/config/risk_policy.json",
        "owner": "Guardian.Policy",
        "purpose": "Durable risk catalog and governance policy, versioned independently from runtime assessments.",
        "freshness": "revision_backed",
    },
    {
        "id": "belief_state",
        "file": "state/local/belief_state.json",
        "owner": "BeliefCore",
        "purpose": "Claims with confidence, source, TTL, and stale/conflict status.",
        "freshness": "ttl_claim_backed",
    },
    {
        "id": "task_state",
        "file": "state/runtime/task_state.json",
        "owner": "AwarenessLoop",
        "purpose": "Current task, route, status, and recent task history.",
        "freshness": "event_scoped",
    },
    {
        "id": "durable_case_state",
        "file": "state/runtime/durable_case_state.json",
        "owner": "Runtime.DurableCaseStore",
        "purpose": "Scoped, revisioned, replay-safe Agent case lifecycle, checkpoints, bounded dialogue records, and pending trace delivery.",
        "freshness": "revision_backed",
    },
    {
        "id": "durable_case_trace",
        "file": "state/logs/durable_case_trace.jsonl",
        "owner": "Runtime.DurableCaseStore",
        "purpose": "Append-only lifecycle evidence recovered from the Durable Case trace outbox.",
        "freshness": "append_only_audit",
    },
    {
        "id": "attention_state",
        "file": "state/runtime/attention_state.json",
        "owner": "AttentionCore",
        "purpose": "Current focus slice, ignored noise, and context scope hints.",
        "freshness": "event_scoped",
    },
    {
        "id": "context_binding_state",
        "file": "state/runtime/context_binding_state.json",
        "owner": "Runtime.ContextBindingStore",
        "purpose": "Exact-owner event sidecars and same-session context hypotheses; no durable ID authority or causal claim.",
        "freshness": "revision_and_expiry_backed",
    },
    {
        "id": "cognitive_loop_state",
        "file": "state/runtime/cognitive_loop_state.json",
        "owner": "Runtime.ReadOnlyCognitiveLoopRuntime",
        "purpose": "Private record-only model interpretations over server-prepared exact-scope cached views; no tool, route, risk, or delivery effect.",
        "freshness": "budget_and_projection_digest_backed",
    },
    {
        "id": "situation_state",
        "file": "state/runtime/situation_state.json",
        "owner": "Core.SituationEvaluator",
        "purpose": "Event-bound Situation projections with immutable source identity and structured non-causal anchors.",
        "freshness": "event_and_revision_backed",
    },
    {
        "id": "event_inbox_state",
        "file": "state/runtime/event_inbox.json",
        "owner": "Runtime.EventInbox",
        "purpose": "Durable exact-event admission, dedupe, claims, leases, completion, and replay metadata without raw message text.",
        "freshness": "append_and_lease_backed",
    },
    {
        "id": "general_situation_state",
        "file": "state/runtime/general_situation_state.json",
        "owner": "Runtime.GeneralSituationRuntime",
        "purpose": "Exact-owner non-causal aggregation of anchored Situations with deterministic child membership.",
        "freshness": "child_projection_backed",
    },
    {
        "id": "attention_hypothesis_state",
        "file": "state/runtime/attention_hypothesis_state.json",
        "owner": "Runtime.AttentionHypothesisRuntime",
        "purpose": "Durable exact-scope attention hypotheses with immutable evidence accumulation and non-factual deterministic readiness.",
        "freshness": "evidence_and_ruleset_backed",
    },
    {
        "id": "suggestion_outbox",
        "file": "state/runtime/suggestion_outbox.json",
        "owner": "Runtime.SuggestionOutbox",
        "purpose": "Private governed suggestion candidates and delivery boundaries; record-only does not notify or execute.",
        "freshness": "revision_backed",
    },
    {
        "id": "project_guardian_attention_state",
        "file": "state/runtime/project_guardian_attention_state.json",
        "owner": "ProjectGuardianAttentionRuntime",
        "purpose": "Bound Attention policies, counterfactual assessments, dismissals, and grouped shadow situations.",
        "freshness": "revision_backed",
    },
    {
        "id": "self_heal_state",
        "file": "state/runtime/self_heal_state.json",
        "owner": "Runtime.OpenClawReconnectPlaybook",
        "purpose": "Versioned target binding, failure confirmations, attempt claims, cooldown, circuit breaker, and review linkage for bounded runtime recovery.",
        "freshness": "revision_backed",
    },
    {
        "id": "sandbox_repair_state",
        "file": "state/runtime/sandbox_repair_state.json",
        "owner": "Runtime.JsonSandboxRepairPlaybook",
        "purpose": "Private JSON candidate claims, exact input bindings, independent verification evidence, and terminal A3 sandbox outcomes; never a workspace or production promotion record.",
        "freshness": "revision_backed",
    },
    {
        "id": "foresight_runtime_state",
        "file": "state/runtime/foresight_runtime_state.json",
        "owner": "Runtime.ForesightRuntime",
        "purpose": "Exact capability-effect assessments and authoritative receipt/effect residuals used only for read-only promotion eligibility.",
        "freshness": "revision_backed",
    },
    {
        "id": "learning_calibration_state",
        "file": "state/runtime/learning_calibration_state.json",
        "owner": "Runtime.LearningCalibrationRuntime",
        "purpose": "Privacy-minimal categorical feedback bound to exact Project Guardian Attention assessments; policy effect is always none.",
        "freshness": "revision_backed",
    },
    {
        "id": "executor_state",
        "file": "state/local/executor_state.json",
        "owner": "AgentAdapter",
        "purpose": "Selected Agent Runtime, connection status, and adapter capability status.",
        "freshness": "probe_backed",
    },
    {
        "id": "persona_state",
        "file": "state/runtime/persona_state.json",
        "owner": "PersonaEngine",
        "purpose": "Active persona modes and channel/risk/Agent binding decisions for recent events.",
        "freshness": "event_scoped",
    },
    {
        "id": "channel_state",
        "file": "state/runtime/channel_state.json",
        "owner": "Interface.ChannelRouter",
        "purpose": "Multi-channel intake sessions, dedupe records, and local outbox delivery records.",
        "freshness": "append_only_runtime",
    },
    {
        "id": "active_loop_state",
        "file": "state/runtime/active_loop_state.json",
        "owner": "Runtime.ActiveRuntimeLoop",
        "purpose": "Continuous awareness loop lifecycle, schedule, recent ticks, and step outcomes.",
        "freshness": "scheduled_runtime",
    },
    {
        "id": "runtime_cron_state",
        "file": "state/runtime/runtime_cron_state.json",
        "owner": "Runtime.Cron",
        "purpose": "Persistent bounded scheduler state for active awareness jobs.",
        "freshness": "scheduled_runtime",
    },
    {
        "id": "replay_runtime_state",
        "file": "state/runtime/replay_runtime_state.json",
        "owner": "RollbackAudit.ReplayRuntime",
        "purpose": "Automatic replay/compensation candidates, review job state, and scan timestamps.",
        "freshness": "audit_derived",
    },
    {
        "id": "execution_trace",
        "file": "state/logs/execution_trace.jsonl",
        "owner": "RollbackAudit.ExecutionTrace",
        "purpose": "Execution evidence linking events, routes, executors, results, and verifier verdicts.",
        "freshness": "append_only_audit",
    },
    {
        "id": "core_model_trace",
        "file": "state/logs/core_model_trace.jsonl",
        "owner": "VeyraCore.CoreReasoning",
        "purpose": "Redacted evidence of Core model-assisted decision, perception, and agency reasoning.",
        "freshness": "append_only_audit",
    },
    {
        "id": "agent_memory",
        "file": "state/user/agent_memory.json",
        "owner": "MemoryBridge",
        "purpose": "Soft user preferences and verified summaries, separate from probe/config/risk facts.",
        "freshness": "quality_and_expiry_backed",
    },
    {
        "id": "event_streams",
        "file": "state/logs/*.jsonl",
        "owner": "WorldState.Retention",
        "purpose": "Append-only event/model/execution streams with bounded rotation and gzip archives.",
        "freshness": "append_only_retained",
    },
]


PHASE5_COMPLETION: dict[str, Any] = {
    "status": "technical_complete_shadow_calibration",
    "validation_state": (
        "local_live_acceptance_validated_remaining_evidence_pending"
    ),
    "global_autonomy_level": None,
    "operational_ceiling": {
        "A2": "selected_openclaw_transport_recovery_only",
        "A3": "veyra_private_json_sandbox_only",
        "A4": "not_certified",
        "A5": "not_certified",
    },
    "control_surfaces": {
        "playbook_registry": "builtin_immutable",
        "foresight": "exact_effect_residual_and_eligibility_only",
        "learning": "exact_categorical_feedback_shadow_only",
        "performance_portfolio": "read_only_no_routing_effect",
        "provider_certification": "fresh_exact_contract_fail_closed",
    },
    "provider_validation": {
        "current_runtime_path": "kimi_via_openclaw",
        "phase5_live_validation": (
            "validated_local_shadow_and_private_a3_canary"
        ),
        "generic_provider_authority": (
            "diagnostic_only_no_dispatch_memory_write_or_stop"
        ),
        "openclaw_dispatch_lock": (
            "fresh_exact_tool_proxy_identity_scope_and_callbacks_per_prompt"
        ),
        "other_agent_runtimes": "validation_pending",
    },
    "validation_evidence": {
        "automated_gate": "64_of_64_passed",
        "openclaw_plugin": "27_of_27_passed",
        "default_shadow": "zero_effects_validated",
        "private_a3_canary": "sandbox_verified_candidate",
        "current_agent_path": (
            "kimi_openclaw_r0_result_observed_without_false_verification"
        ),
    },
    "authority_exclusions": [
        "notification",
        "provider_or_model_auto_switch",
        "process_restart",
        "workspace_read",
        "workspace_mutation",
        "production_effect",
        "candidate_promotion",
        "capability_grant",
        "autonomy_raise",
    ],
}


IMPLEMENTATION_PHASES: list[dict[str, str]] = [
    {"phase": "P0", "name": "Foundation definitions", "status": "completed", "validation_state": "local_self_tested"},
    {"phase": "P1", "name": "State and probe hardening", "status": "completed", "validation_state": "local_self_tested"},
    {"phase": "P2", "name": "Decision, Guardian, and Tool Proxy policy depth", "status": "completed", "validation_state": "local_self_tested"},
    {"phase": "P3", "name": "Agent adapter execution contracts", "status": "completed", "validation_state": "contract_self_tested"},
    {"phase": "P4", "name": "Rollback, audit, and verifier depth", "status": "completed", "validation_state": "local_self_tested"},
    {"phase": "P5", "name": "Web Control Console completeness", "status": "completed", "validation_state": "build_verified"},
    {"phase": "P6", "name": "End-to-end runtime hardening", "status": "implemented", "validation_state": "live_runtime_validation_pending"},
    {"phase": "P7", "name": "Production operations and safety validation", "status": "implemented", "validation_state": "production_soak_validation_pending"},
    {"phase": "P8", "name": "Continuous awareness entity runtime", "status": "implemented", "validation_state": "bounded_local_self_tested"},
    {"phase": "P9", "name": "Chat app integration and guarded automation", "status": "implemented", "validation_state": "feishu_local_openapi_self_tested"},
    {"phase": "P10", "name": "Runtime stabilization and local release hardening", "status": "implemented", "validation_state": "real_feishu_soak_pending"},
]


def architecture_snapshot() -> dict[str, Any]:
    return {
        "blocks": ARCHITECTURE_BLOCKS,
        "core_modules": CORE_MODULES,
        "state_definitions": STATE_DEFINITIONS,
        "risk_levels": risk_catalog(),
        "lifecycle_statuses": lifecycle_statuses(),
        "operational_modes": operational_modes(),
        "phase5_completion": PHASE5_COMPLETION,
        "implementation_phases": IMPLEMENTATION_PHASES,
    }
